"""empty message

Revision ID: 32fb43f86072
Revises: 17985e8a71f0
Create Date: 2017-01-05 01:54:27.383281

"""

# revision identifiers, used by Alembic.
revision = '32fb43f86072'
down_revision = '17985e8a71f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('foo', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('dummy', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dummy')
    op.drop_column('roles', 'foo')
    ### end Alembic commands ###
