"""empty message

Revision ID: 77f70a83a4b3
Revises: 32fb43f86072
Create Date: 2017-01-10 23:50:31.504888

"""

# revision identifiers, used by Alembic.
revision = '77f70a83a4b3'
down_revision = '32fb43f86072'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('obj_id', sa.Integer(), nullable=True),
    sa.Column('obj_type', sa.Unicode(), nullable=True),
    sa.Column('media', sa.String(length=255), nullable=True),
    sa.Column('media_storage_type', sa.String(length=255), nullable=True),
    sa.Column('media_storage_bucket_name', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_storage_type', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_storage_bucket_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    ### end Alembic commands ###
